In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
pick=pd.read_excel('tickdata.xlsx',sheetname='Sheet2')
pick['month'] = pd.DatetimeIndex(pick['date']).month
pick['month_former']=pick['month'].shift(1)
pick['month_former'].fillna(method='bfill',inplace=True)
pick['signal']=np.where(pick['month']==pick['month_former'],0,1)
pick1=pick.iloc[4:1686,:]

In [3]:
class test():
    def __init__(self,net_value=0):
        self.net_value=net_value
        self.record={}
        
    def calculate(self,data):
        if data['signal']==0:
            self.net_value=self.net_value*(1+data['hs300']/100)
        else: 
            self.net_value=(self.net_value+100)*(1+data['hs300']/100)
        return pd.Series({'date':data.date,'net_value':self.net_value})

In [4]:
a=test()
result=pick1.apply(a.calculate,axis=1,result_type='expand')
pick1.merge(result,on='date')

           date   hs300  month  month_former  signal     net_value
0    2013-04-01 -0.0760      4           3.0       1     99.924000
1    2013-04-02 -0.2726      4           4.0       0     99.651607
2    2013-04-03 -0.1144      4           4.0       0     99.537606
3    2013-04-08 -0.4529      4           4.0       0     99.086800
4    2013-04-09  0.6929      4           4.0       0     99.773372
5    2013-04-10 -0.1655      4           4.0       0     99.608247
6    2013-04-11 -0.2991      4           4.0       0     99.310319
7    2013-04-12 -0.6362      4           4.0       0     98.678507
8    2013-04-15 -1.0273      4           4.0       0     97.664783
9    2013-04-16  0.9346      4           4.0       0     98.577558
10   2013-04-17 -0.0455      4           4.0       0     98.532705
11   2013-04-18  0.2594      4           4.0       0     98.788299
12   2013-04-19  2.7984      4           4.0       0    101.552790
13   2013-04-22 -0.1246      4           4.0       0    101.426256
14   2013-04-23 -3.2086      4           4.0       0     98.171893
15   2013-04-24  1.8824      4           4.0       0    100.019881
16   2013-04-25 -1.1101      4           4.0       0     98.909560
17   2013-04-26 -0.8335      4           4.0       0     98.085149
18   2013-05-02  0.0953      5           4.0       1    198.273924
19   2013-05-03  1.7665      5           5.0       0    201.776433
20   2013-05-06  1.3266      5           5.0       0    204.453199
21   2013-05-07  0.1566      5           5.0       0    204.773373
22   2013-05-08  0.5083      5           5.0       0    205.814236
23   2013-05-09 -0.5901      5           5.0       0    204.599726
24   2013-05-10  0.5159      5           5.0       0    205.655256
25   2013-05-13 -0.3962      5           5.0       0    204.840450
26   2013-05-14 -1.4790      5           5.0       0    201.810859
27   2013-05-15  0.5449      5           5.0       0    202.910527
28   2013-05-16  1.8263      5           5.0       0    206.616282
29   2013-05-17  1.5411      5           5.0       0    209.800445
...         ...     ...    ...           ...     ...           ...
1652 2020-01-10 -0.0285      1           1.0       0  10835.924000
1653 2020-01-13  0.9801      1           1.0       0  10942.126891
1654 2020-01-14 -0.3354      1           1.0       0  10905.426998
1655 2020-01-15 -0.5526      1           1.0       0  10845.163608
1656 2020-01-16 -0.4246      1           1.0       0  10799.115044
1657 2020-01-17  0.1400      1           1.0       0  10814.233805
1658 2020-01-20  0.7456      1           1.0       0  10894.864732
1659 2020-01-21 -1.7087      1           1.0       0  10708.704178
1660 2020-01-22  0.4283      1           1.0       0  10754.569558
1661 2020-01-23 -3.0985      1           1.0       0  10421.339220
1662 2020-02-03 -7.8809      2           1.0       1   9692.162998
1663 2020-02-04  2.6375      2           2.0       0   9947.793797
1664 2020-02-05  1.1330      2           2.0       0  10060.502301
1665 2020-02-06  1.8610      2           2.0       0  10247.728248
1666 2020-02-07  0.0024      2           2.0       0  10247.974194
1667 2020-02-10  0.4138      2           2.0       0  10290.380311
1668 2020-02-11  0.9310      2           2.0       0  10386.183752
1669 2020-02-12  0.8088      2           2.0       0  10470.187206
1670 2020-02-13 -0.6152      2           2.0       0  10405.774614
1671 2020-02-14  0.7024      2           2.0       0  10478.864775
1672 2020-02-17  2.2491      2           2.0       0  10714.544923
1673 2020-02-18 -0.4884      2           2.0       0  10662.215085
1674 2020-02-19 -0.1528      2           2.0       0  10645.923221
1675 2020-02-20  2.3041      2           2.0       0  10891.215938
1676 2020-02-21  0.1166      2           2.0       0  10903.915095
1677 2020-02-24 -0.4013      2           2.0       0  10860.157684
1678 2020-02-25 -0.2174      2           2.0       0  10836.547701
1679 2020-02-26 -1.2328      2           2.0       0  10702.954741
1680 2020-02-27  0.2912      2           2.0       0  10734.121746
1681 2020-02-28 -3.5454      2           2.0       0  10353.554193

[1682 rows x 6 columns]

In [5]:
np.rate(nper=83,pmt=100,pv=0,fv=-10353.55,when=1)*12

0.06120062548347825